# Generated by Django 5.1.1 on 2024-10-05 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('required_age', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dlc_count', models.IntegerField()),
                ('about_the_game', models.TextField()),
                ('supported_languages', models.JSONField()),
                ('windows', models.BooleanField(default=False)),
                ('mac', models.BooleanField(default=False)),
                ('linux', models.BooleanField(default=False)),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('score_rank', models.IntegerField()),
                ('developer', models.CharField(max_length=255)),
                ('publishers', models.CharField(max_length=255)),
                ('categories', models.JSONField()),
                ('genres', models.JSONField()),
                ('tags', models.JSONField()),
            ],
        ),
    ]
