# Generated by Django 4.0.4 on 2024-10-06 08:15

import clickhouse_backend.models
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='positive',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='publishers',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='negative_reviews',
            field=clickhouse_backend.models.Int32Field(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='positive_reviews',
            field=clickhouse_backend.models.Int32Field(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='publisher',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='about_the_game',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='app_id',
            field=clickhouse_backend.models.Int32Field(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='categories',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='developer',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='dlc_count',
            field=clickhouse_backend.models.Int32Field(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='genres',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='id',
            field=clickhouse_backend.models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='linux',
            field=clickhouse_backend.models.UInt8Field(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='mac',
            field=clickhouse_backend.models.UInt8Field(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='name',
            field=clickhouse_backend.models.StringField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='price',
            field=clickhouse_backend.models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='release_date',
            field=clickhouse_backend.models.DateField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='required_age',
            field=clickhouse_backend.models.Int32Field(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='score_rank',
            field=clickhouse_backend.models.Int32Field(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='supported_languages',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='tags',
            field=clickhouse_backend.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='windows',
            field=clickhouse_backend.models.UInt8Field(default=0),
        ),
        migrations.AlterModelTable(
            name='gamedata',
            table='game_data',
        ),
    ]
